package main

import "text/template"

// EnumConversionGoTemplate generates Go helper functions for enum string conversion
var EnumConversionGoTemplate = template.Must(template.New("fix.enum.conversion.go").Funcs(templateFuncs).Parse(`// Code generated by generate-pb. DO NOT EDIT.
// This file contains helper functions for converting between protobuf enums and FIX string values.

package {{extractPackageName .GoPackagePrefix}}

import "{{.QuickfixRoot}}/enum"

{{range getAllEnumDefinitions}}
{{.GenerateEnumStringMapping}}{{end}}
`))

// MessageConversionGoTemplate generates conversion functions from FIX messages to protobuf messages
var MessageConversionGoTemplate = template.Must(template.New("fix.message.conversion.go").Funcs(templateFuncs).Parse(`// Code generated by generate-pb. DO NOT EDIT.
// This file contains conversion functions from FIX messages to protobuf messages.

package {{extractPackageName .GoPackagePrefix}}

import (
	"fmt"
{{- range .Packages}}
	"{{.}}"
{{- end}}
)

{{range .Messages}}
// {{.Name}}FromFIX converts a FIX {{.Name}} message to protobuf {{.Name}}
func {{.Name}}FromFIX(fixMsg {{.FIXType}}) (*{{.Name}}, error) {
	pbMsg := &{{.Name}}{}
{{- range .GetFields}}
{{.ConvertCodes}}
{{- end}}
	return pbMsg, nil
}

{{end}}
`))

var GroupConversionGoTemplate = template.Must(template.New("fix.group.conversion.go").Funcs(templateFuncs).Parse(`// Code generated by generate-pb. DO NOT EDIT.
// This file contains conversion functions for FIX components to protobuf messages.

package {{extractPackageName .GoPackagePrefix}}

import (
	"fmt"
    "{{.QuickfixRoot}}/{{.Package}}"
)

{{range .Groups}}
// {{.Name}}FromFIX converts a FIX {{.Name}} group to protobuf {{.Name}} group
func {{.Name}}FromFIX(fixMsg {{.FIXType}}) (*{{.WithoutNoName}}Group, error) {
	pbMsg := &{{.WithoutNoName}}Group{}
{{- range .GetFields}}
{{.ConvertCodes}}
{{- end}}
	return pbMsg, nil
}
{{end}}


`))

//
//func ContAmtsFromFIX(fixMsg fix44.NoContAmts) (*ContAmtsGroup, error) {
//	pbMsg := &ContAmtsGroup{}
//
//	return pbMsg, nil
//}
//
//func ContAmtsRepeatingGroup(fixMsg fix44.NoContAmtsRepeatingGroup) ([]*ContAmtsGroup, error) {
//	pbGroups := make([]*ContAmtsGroup, 0, fixMsg.Len())
//	for i := 0; i < fixMsg.Len(); i++ {
//		pbGroup, err := ContAmtsFromFIX(fixMsg.Get(i))
//		if err != nil {
//			return nil, err
//		}
//		pbGroups = append(pbGroups, pbGroup)
//	}
//	return pbGroups, nil
//}
